### PR TITLE
Upgrade to catch2 v3.4.0, and switch benchmarks to use catch

### PR DESCRIPTION
**Pull request by mdsitton**
Fixes issues #143 and #142

### CODE REVIEW

**Comment by RichieSams** [comment]
Oooo nice! It looks like the CI config needs to be updated (ubuntu-18.04 is no longer supported, as well as OSX something). I can do that, and you can rebase on top

Reviewing your changes...

**Comment by RichieSams** [comment]
Changes look great :)

My only comment is: Should we include catch2 as raw files, or use git submodules? raw files allows us to make edits if we need to, but IMO, we probably won't ever need to with catch2.

If we do keep it as raw files, can we include a txt file or something notating which version / commit you copied from? So when we upgrade in the future, we know which changelog entries to check.

Thoughts? 

(@martty and @BrodyHiggerson for thoughts as well on git submodules or no)

**Comment by RichieSams** [comment]
Can you rebase on master and check that CI passes now?

**Comment by RichieSams** [comment]
Oh, one other pedantic request: You can delete mention of nonius from the README, and remove its licence from LICENSE-THIRD-PARTY

**Comment by mdsitton** [comment]
Unfortunately looks like catch isn't building properly on gcc 9 and the older versions of clang/gcc

**Comment by mdsitton** [comment]
Also additionally i was thinking about this from #140
> We'd only have to bump the tests to c++14 (which they might even already require 🤷‍♂️ ). Which I'm fine with. As you mentioned, 14 is almost 10 years old now

Is it really a good idea to not support testing on potentially "supported" c++11 compilers since there wouldn't be much validation happening there with testing.

**Comment by mdsitton** [comment]
With that said technically gcc 5 should be fine with C++14 looking at what the version supports so seems like potentially some issue with catch.

**Comment by mdsitton** [comment]
Looking over the log more 
		Check_And_Add_Flag(${TARGET} -Wno-aligned-new)
is also causing an error on gcc 5 from:
cmake\AddCompilerFlags.cmake
https://dev.azure.com/adastley/adastley/_build/results?buildId=179&view=logs&j=75da2154-1c41-5424-3a3b-cd670808b5e4&t=c9fb99c5-dcdd-5bdf-ac8d-6b4ca6067273&l=428

Which is the only additional error over gcc 9

**Comment by mdsitton** [comment]
Actually yeah another one of these is causing the other error:
		Check_And_Add_Flag(${TARGET} -Wctor-dtor-privacy)

**Comment by RichieSams** [comment]
I'm also fine with dropping gcc 5 and clang 3.7 for CI purposes

**Comment by mdsitton** [comment]
That last commit probably needs a bit more work to set the cmake variable names correctly, but basically the jist of the issue can be found here:
https://gcc.gnu.org/wiki/FAQ#wnowarning
`if the -Wno- form is used, the behavior is slightly different: no diagnostic is produced for -Wno-unknown-warning unless other diagnostics are being produced. `
Basically this means that CHECK_CXX_COMPILER_FLAG isn't going to work properly with -Wno- flags so we have to instead test the reverse of the flag to determine if it's available.

**Comment by mdsitton** [comment]
@RichieSams Any thoughts on clang here? We might should consider increasing the version being used for testing since clearly it has some kind of issues with unique_ptr that the other compilers don't have.

**Comment by mdsitton** [comment]
Also i refreshed after i sent that and now i see your message, i think we should probably just increase the version of clang being tested on linux a bit rather than totally dropping it. And i got gcc 5 working anyways so it's fine.

**Comment by RichieSams** [comment]
sorry, clarification. Just meant dropping the lower versions of clang. IE, just using clang 12 and 16 like we do for OSX

**Comment by RichieSams** [comment]
Ok rebase again

**Comment by mdsitton** [comment]
Ok so everything should be good to merge now if you are happy with it.

**Comment by RichieSams** [comment]
Woohoo! Congratulations on your first contribution. And thank you very much :)

**Comment by mdsitton** [comment]
Of course now onto #141 :)

**Pull request merged**
