### PR TITLE
Fix iterator debug level

### PR DESCRIPTION
**Pull request by BrodyHiggerson**

### CODE REVIEW

**Comment by BrodyHiggerson** [comment]
Used wrong base - will fix on my side

**Comment by RichieSams** [comment]
IMO, I would name it `FTL_ITERATOR_DEBUG_LEVEL` , to be more explicit about what it controls. Otherwise, looks good to me.

If you want, I can squash and merge the no main task branch first

**Comment by BrodyHiggerson** [comment]
> 
> 
> IMO, I would name it `FTL_ITERATOR_DEBUG_LEVEL` , to be more explicit about what it controls. Otherwise, looks good to me.
> 
> If you want, I can squash and merge the no main task branch first

Sure - would you expect the option would be setting the level? I.e. the user specifies 0, 1, 2? Alternatively, it could be a setting to only override in debug? So release is always fast. What do you think?

**Comment by RichieSams** [comment]
Good point. We want the default to do nothing, and leave what they have. And the override to set what they say. Maybe we have the default as -1. And in that case we dont add a flag. And for others we apply what they give.

**Comment by BrodyHiggerson** [comment]
> 
> 
> Good point. We want the default to do nothing, and leave what they have. And the override to set what they say. Maybe we have the default as -1. And in that case we dont add a flag. And for others we apply what they give.

Hmm, can't have non-binary options.

**Comment by RichieSams** [comment]
Closing in favor of 235d2ef9f95096deb1574ab42cc319ac4f505708

**Pull request closed without merging**
