### PR TITLE
Fix First Thread Affinity

### LINKED ISSUE #59: Program Only Using N-1 Cores on Linux
This sets the first thread to affinity 1, then later on you set the other N-1 threads to 1,2,3 on a 4 core, meaning there are two threads sharing affinity. Setting this to zero, makes it work with no issues. I'll file a PR.

https://github.com/RichieSams/FiberTaskingLib/blob/master/source/task_scheduler.cpp#L274

### PR DESCRIPTION
**Pull request by cwfitzgerald**
Will close #59.

### CODE REVIEW

**Comment by RichieSams** [comment]
Thanks! Great find.

Similar to the previous PR, I'll fix up the Mac issues and then we can merge this fix

**Comment by cwfitzgerald** [comment]
Sounds good!

**Comment by RichieSams** [comment]
I wish there was a better way to re-kick the CI than to close and re-open....
Just waiting on CI, then I'll merge. Thanks again for the fixes!!

**Comment by RichieSams** [comment]
Unfortunately, that won't reload the .travis.yml. It re-runs the same configuration.
But if it's only code changes, then that should work. Thanks!

**Comment by cwfitzgerald** [comment]
How'd you change my branch's travis.yml without adding a commit?

**Comment by RichieSams** [comment]
I think it builds against the upstream repo's travis.yml for pull requests. I updated my travis.yml in https://github.com/RichieSams/FiberTaskingLib/commit/55b28c547654afbdac4c4d7f5d721eded54ee787. And I needed to re-kick so your PR's would rebase on top of the new master.

**Comment by cwfitzgerald** [comment]
Huh. Didn't know that. Cool, thanks! Also, this library is really awesome 😄

**Pull request merged**
