### PR TITLE
fcontext asm update: Windows kernel calls work from fibers (x64)

### PR DESCRIPTION
**Pull request by martty**
I pulled some updated asm code from boost context, which allows to make system calls in a fiber without crashing (tested Debug and Release). I think this problem exists also on x86, and I only committed the files for masm, since this is the one that I can test now, but the other asm files could be updated in a similar manner.
Solves issue #26?

### CODE REVIEW

**Comment by RichieSams** [comment]
Ooo, good idea. What version of boost are these pulled from? I can do a systematic upgrade and check of the other asm files.

**Comment by martty** [comment]
Yeah, sorry, should've included that:
https://github.com/boostorg/context/commit/da5865406a66cf00c2664cecb94114cfffdaae01

**Comment by RichieSams** [comment]
I'm a tad worried about that particular version. It does not save the MMX registers. So any floating point data will be corrupted / lost between context switches. I'm going to try to integrate the latest version of the asm.

**Comment by RichieSams** [comment]
I have pulled and modified the latest boost (roughly 1.63) and pushed to master. See 53018a1c90efa0bc95e1b573346b0852c929da03 and 978f8676c7d8d5ae3e3127d79c73cb904d94bb95. I'm slowly re-adding more platforms as soon as I can test each of them. (I'll boot up my RaspberryPi this week and re-add ARM).

As a result, I'm going to close this pull request. That said, I'm extremely grateful for your effort, and for suggesting to update boost.

I'm planning to add some more unit tests. Perhaps one to check that FP registers are being properly saved, and another for system calls.

**Comment by martty** [comment]
Thanks very much for getting to the bottom of it! I'm getting around to integrating FTL with my codebase, so I'll try to contribute some more in the future.

**Pull request closed without merging**
